### ISSUE TITLE
Составить инфу для выпадающих списков

### ISSUE THREAD

**Issue by Bubusara0505** [ynambell/owoce-project#5]
Servises
Progects
News
Shop

**Comment by ynambell** [comment]
**Servises -** 
* Imperfect Food Box
* Green Chef Box
**Projects -** 
* Meet the Farmers
* Harvest Festival
**News -** 
* Bringing Food Production Back To Cities
* The Future of Farming, Smart Irrigation Solutions
**Shop -** 
* Agriculture
* Farming
* Fresh Vegatables
* Harvest
* Organic Food
